name: Compilar App iOS

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Listar archivos subidos
      run: |
        echo "Contenido del repositorio:"
        ls -la
        echo "Buscando archivos .xcodeproj:"
        find . -name "*.xcodeproj"
    
    - name: Compilar
      run: |
        # Encontrar el archivo .xcodeproj
        PROJECT=$(find . -name "*.xcodeproj" | head -n 1)
        echo "Proyecto encontrado: $PROJECT"
        
        # Compilar
        xcodebuild clean build \
          -project "$PROJECT" \
          -scheme appciudad \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
          -configuration Debug \
          -derivedDataPath ./build
    
    - name: Encontrar y comprimir .app
      run: |
        APP_PATH=$(find ./build -name "*.app" -type d | head -n 1)
        echo "App encontrada en: $APP_PATH"
        cd $(dirname "$APP_PATH")
        zip -r $GITHUB_WORKSPACE/appciudad.app.zip $(basename "$APP_PATH")
    
    - name: Subir artefacto
      uses: actions/upload-artifact@v4
      with:
        name: appciudad-ios
        path: appciudad.app.zip
        retention-days: 7

